### ISSUE TITLE
Is it possible to create multi-architecture APK?

### ISSUE THREAD

**Issue by CapSel** [skanti/Android-Manual-Build-Command-Line#1]

**Comment by skanti** [comment]
Hi there,
good question. I think it is not possible all in one `apk` - but that is merely a guess. What I know is certainly possible is to build for many architectures ( `mips, x86, x86-64, arm, arm64`) as a big bundle and upon deployment/run-time the target device will pick the correct one. That is how it works in the `google play` store anyway. That is a standard technique - Android Studio has designated check boxes for that.

Hope I could help.
