### ISSUE TITLE
Trying to follow your sample...

### ISSUE THREAD

**Issue by raysan5** [skanti/Android-Manual-Build-Command-Line#2]
Hi @skanti, just writting here because I couldn't find an email.

I'm trying to support "simple" Makefile building for Android projects for [raylib](https://github.com/raysan5/raylib). Right now it's the only supported platform that uses another build system other than plain Makefiles.

After LOT of research I found your project, probably the best reference in the net for a custom and simple Android APK building by command line, I tried to generate Makefiles with CMake but it didn't work.

Would it be possible to get a plain Makefile with all the required targets to build an Android project from command line, or maybe just get the cmd lines required? --> GOT IT!

Another question: Does your current implementation support assets/resources building? --> WORKING on IT...

**UPDATE 1**: Looking at `CMakeList.txt` more carefully, I can get command line steps directly from there. Still wondering about assets/resources building...

**UPDATE 2**: Just got command lines and testing it, also testing resources embedding with `aapt -A` command...  

I think I dropped the issue too soon... in any case, thank you very much for such a great sample!

**Comment by skanti** [comment]
Hi, I am glad you figured out both answers :) Yes just to recap, it has `makefile` support and you can import assets with the `aapt -A` flag like you already foud out.

Cheers

**Comment by raysan5** [comment]
Hi @skanti, thanks for your answer!

Just implemented the [Makefile for a simple raylib project](https://github.com/raysan5/raylib/blob/develop/templates/android_project/Makefile).

It compiles ok and generates the .APK, I'll try to deploy to device and let you know...

**Comment by raysan5** [comment]
Hi @skanti, after some work, APK seems to generate ok but it doesn't work when trying to deploy to device... I think I'm missing something... more info here: https://github.com/raysan5/raylib/issues/278

I'm stuck with this issue, maybe you can spot some problem with the building process?
