### ISSUE TITLE
Cannot run makefile command line

### ISSUE THREAD

**Issue by nambv** [skanti/Android-Manual-Build-Command-Line#3]
Hi @skanti ,
I am trying to using makefile to build android application. When I used your tool, I received this error during the command line: `make build`

```
error: 'malloc' was not declared in this scope
             engine->app->savedState = malloc(sizeof(struct saved_state));
```

Can you take a look? Thank you very much for your support

**Comment by skanti** [comment]
Hi, can you include  the header ` <cstdlib>`? That should resolve the problem
